name: Create master pull request
on:
  push:
    branches:
      - developer
jobs:
  sychMaster:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
      - uses: actions/checkout@v2
        with:
          ref: master
