name: Compare master with developer to merge
on:
  push:
    branches:
      - developer
jobs:
  barnch-merge:
    name: Merge Job
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
      - uses: actions/checkout@v2
